services:
  - type: web
    name: getiva-tracking-system
    runtime: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PORT
        value: 8000

